services:
  app:
    container_name: 'application'
    build: src
    environment:
      - OPENKEY=a60abf2eb6b714d0d48ed9509e924f9a
      - AWS_ACCESS_KEY_ID=devgrid
      - AWS_SECRET_ACCESS_KEY=devgrid
      - SQS_QUEUE_NAME=devgrid
      - AWS_ENDPOINT_URL=http://localstack:4566/
      - AWS_DEFAULT_REGION=us-east-1
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_NAME=postgresql
      - POSTGRESQL_DATABASE=postgres
      - SQS_URL=http://localstack:4566/000000000000/devgrid
    ports:
      - 8000:8000
    networks:
      - devgrid_net

    command:  bash -c "awslocal sqs create-queue --queue-name devgrid && fastapi run app.py"

  agent:
    container_name: 'agent'
    build: src
    environment:
      - OPENKEY=a60abf2eb6b714d0d48ed9509e924f9a
      - AWS_ACCESS_KEY_ID=devgrid
      - AWS_SECRET_ACCESS_KEY=devgrid
      - SQS_QUEUE_NAME=devgrid
      - AWS_ENDPOINT_URL=http://localstack:4566/
      - AWS_DEFAULT_REGION=us-east-1
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_NAME=postgresql
      - POSTGRESQL_DATABASE=postgres
      - SQS_URL=http://localstack:4566/000000000000/devgrid
    depends_on:
      - app
    networks:
      - devgrid_net

    command: bash -c "python start_thread_observer.py"

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./local_data/localstack/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

    networks:
      - devgrid_net

  postgresql:
    container_name: 'database'
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    ports:
      - '5432:5432'

    networks:
      - devgrid_net

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning

    networks:
      - devgrid_net

networks:
  devgrid_net:
    name: devgrid_network